######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 22 21:35:28 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += opengl

# Input
HEADERS += game.h player.h scene.h
SOURCES += game.cc main.cc player.cc scene.cc
