######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 24 14:33:22 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += opengl

QMAKE_CXXFLAGS += -std=c++11

# Input
HEADERS += game.h obstacle.h obstacle_manager.h player.h scene.h
SOURCES += game.cc main.cc obstacle.cc obstacle_manager.cc player.cc scene.cc
